config/routes.rb
Rails.application.routes.draw do
  get 'cohorts/index'

  get 'cohorts/show'

  get 'cohorts/new'

  get 'cohorts/edit'

  get 'site/index'

  root 'site#index'

  resources :cohorts
  resources :students

end

app/models/cohort.rb
class Cohort < ActiveRecord::Base
  has_and_belongs_to_many :students
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_and_belongs_to_many :cohorts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  def index
    @cohorts = Cohort.all
  end

  def show
    @cohort = Cohort.find(params[:id])
  end

  def new
    @cohort = Cohort.new
  end

  def create
    cohort = Cohort.create(cohort_params)

    redirect_to cohort_url(cohort)
  end

  def edit
    @cohort = Cohort.find(params[:id])
  end

  def update
    cohort = Cohort.find(params[:id])
    cohort.update(cohort_params)

    redirect_to cohort_url(cohort)
  end

  def destroy
    @cohort = Cohort.find(params[:id])
    @cohort.destroy

    redirect_to cohorts_url
  end

  private

  def cohort_params
    params.require(:cohort).permit(:name)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/cohorts/_form.html.erb
<%= form_for @cohort do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/cohorts/edit.html.erb
<h1>Edit <%= @cohort.name %></h1>

<%= render partial: "form" %>

app/views/cohorts/index.html.erb
<h1>Cohorts</h1>

<p><%= link_to "Add a cohort", new_cohort_url, class: "btn btn-success" %></p>

<ul>
  <% @cohorts.each do |cohort| %>
    <li>
      <%= link_to cohort.name, cohort_url(cohort) %>
      [<%= link_to "edit", edit_cohort_url(cohort) %>]
      [<%= link_to "delete", cohort_url(cohort), method: :delete, confirm: "Are you sure?" %>]
    </li>
  <% end %>
</ul>

app/views/cohorts/new.html.erb
<h1>Add a new cohort</h1>

<%= render partial: "form" %>

app/views/cohorts/show.html.erb
<h1><%= @cohort.name %></h1>

<ul>
  <% @cohort.students.each do |student| %>
    <li><%= student.name %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movico</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
<%= yield %>
  </div>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>
</html>

app/views/site/index.html.erb
<h1>Woo hoo!</h1>
<p>Hi, there!</p>